export const CATEGORIES_ACTION_TYPE = {
    SET_CATEGORIES_FETCH_START : "SET_CATEGORIES_START ",
    SET_CATEGORIES_FETCH_SUCESS : "SET_CATEGORIES_SUCESS",
    SET_CATEGORIES_FETCH_FAIL : "SET_CATEGORIES_FAIL",

}